services:
  web:
    build: .
    env_file: ".env"
    ports:
      - "4000:4000"
    depends_on:
      - "postgres"
    restart: "always"
  postgres:
    image: "postgres:14-alpine"
    env_file: ".env"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    restart: "always"
  migration:
    build: .
    env_file: ".env"
    depends_on:
      - web
      - postgres
    command: bin/migrate
    restart: "no"
  caddy:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    command: caddy reverse-proxy --from https://example.com:443 --to http://web:4000
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
    depends_on:
      - web
volumes:
  postgres: {}
  caddy: {}